services:
    kora_grid.grid_factory:
        class: Kora\GridBundle\GridFactory
        arguments:
            - '@kora_grid.form_builder'

    kora_grid.form_builder:
        class: Kora\GridBundle\FormBuilder\FormBuilder
        arguments:
            - '@form.factory'

    kora_grid.form.choice_filter:
        class: Kora\GridBundle\FormBuilder\FilterFormTypes\ChoiceFilterFormType
        tags:
            -
                name: kora_grid.filter_form
                filter: "Kora\\DataProvider\\OperatorDefinition\\Filter\\ChoiceFilterDefinition"

    kora_grid.form.date_range:
        class: Kora\GridBundle\FormBuilder\FilterFormTypes\DateRangeFilterFormType
        tags:
            -
                name: kora_grid.filter_form
                filter: "Kora\\DataProvider\\OperatorDefinition\\Filter\\DateRangeFilterDefinition"